// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv0CToJ8_wajfstsd-m4MF4xw4BaIxeIY',
    appId: '1:334594413897:web:90ad316b7494ee8e8cb698',
    messagingSenderId: '334594413897',
    projectId: 'cafe-books-7cd1a',
    authDomain: 'cafe-books-7cd1a.firebaseapp.com',
    storageBucket: 'cafe-books-7cd1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3NrRpcAS1c5HCJOmqpfxz4H6FyPEG9Rs',
    appId: '1:334594413897:android:719168d2c3710ef68cb698',
    messagingSenderId: '334594413897',
    projectId: 'cafe-books-7cd1a',
    storageBucket: 'cafe-books-7cd1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1_Whnm9G-N6ymIPwl2r0_1bcnVK2apMc',
    appId: '1:334594413897:ios:a82cc32172f9402f8cb698',
    messagingSenderId: '334594413897',
    projectId: 'cafe-books-7cd1a',
    storageBucket: 'cafe-books-7cd1a.appspot.com',
    iosClientId: '334594413897-li30vmaf3sb0apeenbhjb603dph5dctu.apps.googleusercontent.com',
    iosBundleId: 'com.rendersoft.cafeBooks',
  );
}
